spring.application.name=Cinema

spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_db
spring.datasource.username=admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Execute data.sql after Hibernate creates tables
# spring.sql.init.mode=always
# spring.jpa.defer-datasource-initialization=true

server.servlet.context-path=/cinema

# Debug view resolution and Freemarker auto-configuration
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.boot.autoconfigure.freemarker=DEBUG
logging.level.org.springframework.web=DEBUG

# Freemarker explicit settings to ensure templates are resolved
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl
spring.freemarker.charset=UTF-8
spring.freemarker.check-template-location=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.allow8bitmime=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

app.base-url=http://localhost:8080/cinema